/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection } from '@angular/fire/firestore';
import { Observable } from 'rxjs';

// Import Services
import { MemberService } from '../../services/member.service';
import { HabitService } from '../../services/habit.service';
import { JournalEntryService } from '../../services/journal-entry.service';
import { EvaluationService } from '../../services/evaluation.service';
import { InterpretationService } from '../../services/interpretation.service';
import { CommentService } from '../../services/comment.service';

import { Member } from '../../domain/habitopia_db/member';
import { Habit } from '../../domain/habitopia_db/habit';
import { JournalEntry } from '../../domain/habitopia_db/journal-entry';
import { Evaluation } from '../../domain/habitopia_db/evaluation';
import { Interpretation } from '../../domain/habitopia_db/interpretation';
import { Comment } from '../../domain/habitopia_db/comment';

// START - USED SERVICES
/**
* MemberService.create
*	@description CRUD ACTION create
*
* HabitService.findBymember
*	@description CRUD ACTION findBymember
*	@param Objectid key Id della risorsa member da cercare
*
* JournalEntryService.findBymember
*	@description CRUD ACTION findBymember
*	@param Objectid key Id della risorsa member da cercare
*
* EvaluationService.findBymember
*	@description CRUD ACTION findBymember
*	@param Objectid key Id della risorsa member da cercare
*
* InterpretationService.findBymember
*	@description CRUD ACTION findBymember
*	@param Objectid key Id della risorsa member da cercare
*
* CommentService.findBymember
*	@description CRUD ACTION findBymember
*	@param Objectid key Id della risorsa member da cercare
*
* JournalEntryService.findBymemberTarger
*	@description CRUD ACTION findBymemberTarger
*	@param Objectid key Id della risorsa memberTarger da cercare
*
* MemberService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* MemberService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a  Member
 */
@Component({
    selector: 'app-member-edit',
    templateUrl: 'member-edit.component.html',
    styleUrls: ['member-edit.component.css']
})
export class MemberEditComponent implements OnInit {
    item: any = {};
    itemDoc: AngularFirestoreDocument<Member>;
    isNew: Boolean = true;
    formValid: Boolean;

    listMember: Member[];
    listMemberTarger: Member[];

    externalHabit: Habit[];
    externalJournalEntry: JournalEntry[];
    externalEvaluation: Evaluation[];
    externalInterpretation: Interpretation[];
    externalComment: Comment[];

    constructor(
        private memberService: MemberService,
        private habitService: HabitService,
        private journalentryService: JournalEntryService,
        private evaluationService: EvaluationService,
        private interpretationService: InterpretationService,
        private commentService: CommentService,
        private route: ActivatedRoute,
        private location: Location) {
        // Init list
        this.externalHabit = [];
        this.externalJournalEntry = [];
        this.externalEvaluation = [];
        this.externalInterpretation = [];
        this.externalComment = [];
        this.externalJournalEntry = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.isNew = false;
                this.itemDoc = this.memberService.get(id);
                this.itemDoc.valueChanges().subscribe(item => this.item = item);

                this.habitService.findByMember(id).subscribe(list => this.externalHabit = list);
                this.journalentryService.findByMember(id).subscribe(list => this.externalJournalEntry = list);
                this.evaluationService.findByMember(id).subscribe(list => this.externalEvaluation = list);
                this.interpretationService.findByMember(id).subscribe(list => this.externalInterpretation = list);
                this.commentService.findByMember(id).subscribe(list => this.externalComment = list);
                this.journalentryService.findByMemberTarger(id).subscribe(list => this.externalJournalEntry = list);
            }
            // Get relations
        });
    }



    /**
     * Save Member
     *
     * @param {boolean} formValid Form validity check
     * @param Member item Member to save
     */
    save(formValid: boolean): void {
        this.formValid = formValid;
        if (formValid) {
            if (this.isNew) {
                // Create
                this.memberService.create(this.item);
                this.isNew = false;
            } else {
                // Update
                this.memberService.update(this.itemDoc, this.item);
            }
            this.goBack();
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }

}
