/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection } from '@angular/fire/firestore';
import { Observable } from 'rxjs';

// Import Services
import { CommentService } from '../../services/comment.service';
import { LogEntryService } from '../../services/log-entry.service';
import { MemberService } from '../../services/member.service';

import { Comment } from '../../domain/habitopia_db/comment';
import { LogEntry } from '../../domain/habitopia_db/log-entry';
import { Member } from '../../domain/habitopia_db/member';
import { Comment } from '../../domain/habitopia_db/comment';

// START - USED SERVICES
/**
* CommentService.create
*	@description CRUD ACTION create
*
* LogEntryService.findBycomment
*	@description CRUD ACTION findBycomment
*	@param Objectid key Id della risorsa comment da cercare
*
* CommentService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* MemberService.list
*	@description CRUD ACTION list
*
* CommentService.list
*	@description CRUD ACTION list
*
* CommentService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a  Comment
 */
@Component({
    selector: 'app-comment-edit',
    templateUrl: 'comment-edit.component.html',
    styleUrls: ['comment-edit.component.css']
})
export class CommentEditComponent implements OnInit {
    item: any = {};
    itemDoc: AngularFirestoreDocument<Comment>;
    isNew: Boolean = true;
    formValid: Boolean;

    listComment: Comment[];
    listMember: Member[];
    listParentComment: Comment[];

    externalLogEntry: LogEntry[];

    constructor(
        private commentService: CommentService,
        private logentryService: LogEntryService,
        private memberService: MemberService,
        private route: ActivatedRoute,
        private location: Location) {
        // Init list
        this.externalLogEntry = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.isNew = false;
                this.itemDoc = this.commentService.get(id);
                this.itemDoc.valueChanges().subscribe(item => this.item = item);

                this.logentryService.findByComment(id).subscribe(list => this.externalLogEntry = list);
            }
            // Get relations
            this.memberService.list().subscribe(list => this.listMember = list);
            this.commentService.list().subscribe(list => this.listParentComment = list);
        });
    }



    /**
     * Save Comment
     *
     * @param {boolean} formValid Form validity check
     * @param Comment item Comment to save
     */
    save(formValid: boolean): void {
        this.formValid = formValid;
        if (formValid) {
            if (this.isNew) {
                // Create
                this.commentService.create(this.item);
                this.isNew = false;
            } else {
                // Update
                this.commentService.update(this.itemDoc, this.item);
            }
            this.goBack();
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }

}
