/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection } from '@angular/fire/firestore';
import { Observable } from 'rxjs';

// Import Services
import { LogEntryService } from '../../services/log-entry.service';
import { HabitService } from '../../services/habit.service';
import { JournalEntryService } from '../../services/journal-entry.service';
import { InterpretationService } from '../../services/interpretation.service';
import { EvaluationService } from '../../services/evaluation.service';
import { CommentService } from '../../services/comment.service';

import { LogEntry } from '../../domain/habitopia_db/log-entry';
import { Comment } from '../../domain/habitopia_db/comment';
import { Evaluation } from '../../domain/habitopia_db/evaluation';
import { Habit } from '../../domain/habitopia_db/habit';
import { Interpretation } from '../../domain/habitopia_db/interpretation';
import { JournalEntry } from '../../domain/habitopia_db/journal-entry';

// START - USED SERVICES
/**
* LogEntryService.create
*	@description CRUD ACTION create
*
* LogEntryService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* HabitService.list
*	@description CRUD ACTION list
*
* JournalEntryService.list
*	@description CRUD ACTION list
*
* InterpretationService.list
*	@description CRUD ACTION list
*
* EvaluationService.list
*	@description CRUD ACTION list
*
* CommentService.list
*	@description CRUD ACTION list
*
* LogEntryService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a  LogEntry
 */
@Component({
    selector: 'app-log-entry-edit',
    templateUrl: 'log-entry-edit.component.html',
    styleUrls: ['log-entry-edit.component.css']
})
export class LogEntryEditComponent implements OnInit {
    item: any = {};
    itemDoc: AngularFirestoreDocument<LogEntry>;
    isNew: Boolean = true;
    formValid: Boolean;

    listComment: Comment[];
    listEvaluation: Evaluation[];
    listHabit: Habit[];
    listInterpretation: Interpretation[];
    listJournalEntry: JournalEntry[];


    constructor(
        private logentryService: LogEntryService,
        private habitService: HabitService,
        private journalentryService: JournalEntryService,
        private interpretationService: InterpretationService,
        private evaluationService: EvaluationService,
        private commentService: CommentService,
        private route: ActivatedRoute,
        private location: Location) {
        // Init list
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.isNew = false;
                this.itemDoc = this.logentryService.get(id);
                this.itemDoc.valueChanges().subscribe(item => this.item = item);

            }
            // Get relations
            this.commentService.list().subscribe(list => this.listComment = list);
            this.evaluationService.list().subscribe(list => this.listEvaluation = list);
            this.habitService.list().subscribe(list => this.listHabit = list);
            this.interpretationService.list().subscribe(list => this.listInterpretation = list);
            this.journalentryService.list().subscribe(list => this.listJournalEntry = list);
        });
    }



    /**
     * Save LogEntry
     *
     * @param {boolean} formValid Form validity check
     * @param LogEntry item LogEntry to save
     */
    save(formValid: boolean): void {
        this.formValid = formValid;
        if (formValid) {
            if (this.isNew) {
                // Create
                this.logentryService.create(this.item);
                this.isNew = false;
            } else {
                // Update
                this.logentryService.update(this.itemDoc, this.item);
            }
            this.goBack();
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }

}
