/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE commentBaseService PLEASE EDIT ../comment.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Comment } from '../../domain/habitopia_db/comment';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Comment.service.ts
 */

/*
 * SCHEMA DB Comment
 *
	{
		comment: {
			type: 'String',
			required : true
		},
		date: {
			type: 'Date',
			required : true
		},
		votes: {
			type: 'Custom'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		comment: {
			type: Schema.ObjectId,
			ref : "LogEntry"
		},
		member: {
			type: Schema.ObjectId,
			ref : "Comment"
		},
		parentComment: {
			type: Schema.ObjectId,
			ref : "Comment"
		},
	}
 *
 */
@Injectable()
export class CommentBaseService {

    private commentCollection: AngularFirestoreCollection<Comment>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.commentCollection = afs.collection<Comment>('comment');
    }


    // CRUD METHODS

    /**
    * CommentService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Comment): Promise<DocumentReference> {
        return this.commentCollection.add(item);
    }

    /**
    * CommentService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.commentCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * CommentService.findBymember
    *   @description CRUD ACTION findBymember
    *   @param Objectid key Id della risorsa member da cercare
    *
    */
    findByMember(id: string): Observable<any[]> {
        return this.afs.collection('comment', ref => ref.where('member', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Comment;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * CommentService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Comment> {
        return this.afs.doc<Comment>('comment/' + id);
    }

    /**
    * CommentService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Comment[]> {
        return this.afs.collection('comment').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Comment;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * CommentService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Comment>, item: Comment): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
