/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE cueBaseService PLEASE EDIT ../cue.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Cue } from '../../domain/habitopia_db/cue';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Cue.service.ts
 */

/*
 * SCHEMA DB Cue
 *
	{
		endTime: {
			type: 'Date',
			required : true
		},
		latitude: {
			type: 'Decimal'
		},
		longitude: {
			type: 'Decimal'
		},
		name: {
			type: 'String',
			required : true
		},
		startTime: {
			type: 'Date'
		},
		type: {
			type: 'String',
			required : true,
			enum : ["CLOUD_MESSAGE", "HABIT", "PHYSICAL_EVENT", "TIME_AND_LOCATION", "TIME_OF_DAY"]
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		cue: {
			type: Schema.ObjectId,
			ref : "Habit"
		},
		preceedingHabit: {
			type: Schema.ObjectId,
			ref : "Cue"
		},
	}
 *
 */
@Injectable()
export class CueBaseService {

    private cueCollection: AngularFirestoreCollection<Cue>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.cueCollection = afs.collection<Cue>('cue');
    }


    // CRUD METHODS

    /**
    * CueService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Cue): Promise<DocumentReference> {
        return this.cueCollection.add(item);
    }

    /**
    * CueService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.cueCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * CueService.findBypreceedingHabit
    *   @description CRUD ACTION findBypreceedingHabit
    *   @param Objectid key Id della risorsa preceedingHabit da cercare
    *
    */
    findByPreceedingHabit(id: string): Observable<any[]> {
        return this.afs.collection('cue', ref => ref.where('preceedingHabit', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Cue;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * CueService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Cue> {
        return this.afs.doc<Cue>('cue/' + id);
    }

    /**
    * CueService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Cue[]> {
        return this.afs.collection('cue').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Cue;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * CueService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Cue>, item: Cue): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
