/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE habitBaseService PLEASE EDIT ../habit.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Habit } from '../../domain/habitopia_db/habit';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Habit.service.ts
 */

/*
 * SCHEMA DB Habit
 *
	{
		name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		action: {
			type: Schema.ObjectId,
			ref : "Habit"
		},
		cue: {
			type: Schema.ObjectId,
			ref : "Habit"
		},
		habit: {
			type: Schema.ObjectId,
			ref : "LogEntry"
		},
		member: {
			type: Schema.ObjectId,
			ref : "Habit"
		},
		preceedingHabit: {
			type: Schema.ObjectId,
			ref : "Cue"
		},
		rewards: [{
			type: Schema.ObjectId,
			ref : "Habit"
		}],
	}
 *
 */
@Injectable()
export class HabitBaseService {

    private habitCollection: AngularFirestoreCollection<Habit>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.habitCollection = afs.collection<Habit>('habit');
    }


    // CRUD METHODS

    /**
    * HabitService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Habit): Promise<DocumentReference> {
        return this.habitCollection.add(item);
    }

    /**
    * HabitService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.habitCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * HabitService.findByaction
    *   @description CRUD ACTION findByaction
    *   @param Objectid key Id della risorsa action da cercare
    *
    */
    findByAction(id: string): Observable<any[]> {
        return this.afs.collection('habit', ref => ref.where('action', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Habit;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * HabitService.findBycue
    *   @description CRUD ACTION findBycue
    *   @param Objectid key Id della risorsa cue da cercare
    *
    */
    findByCue(id: string): Observable<any[]> {
        return this.afs.collection('habit', ref => ref.where('cue', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Habit;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * HabitService.findBymember
    *   @description CRUD ACTION findBymember
    *   @param Objectid key Id della risorsa member da cercare
    *
    */
    findByMember(id: string): Observable<any[]> {
        return this.afs.collection('habit', ref => ref.where('member', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Habit;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * HabitService.findByrewards
    *   @description CRUD ACTION findByrewards
    *   @param Objectid key Id della risorsa rewards da cercare
    *
    */
    findByRewards(id: string): Observable<any[]> {
        return this.afs.collection('habit', ref => ref.where('rewards', 'array-contains', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Habit;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * HabitService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Habit> {
        return this.afs.doc<Habit>('habit/' + id);
    }

    /**
    * HabitService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Habit[]> {
        return this.afs.collection('habit').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Habit;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * HabitService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Habit>, item: Habit): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
