/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE interpretationBaseService PLEASE EDIT ../interpretation.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Interpretation } from '../../domain/habitopia_db/interpretation';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Interpretation.service.ts
 */

/*
 * SCHEMA DB Interpretation
 *
	{
		elements: {
			type: 'Custom'
		},
		interpretation: {
			type: 'String',
			required : true
		},
		source: {
			type: 'String',
			required : true,
			enum : ["DarkRealm", "God", "GoodEntities", "OtherPeople", "Person"]
		},
		votes: {
			type: 'Custom'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		action: {
			type: Schema.ObjectId,
			ref : "Interpretation"
		},
		entry: {
			type: Schema.ObjectId,
			ref : "Interpretation"
		},
		interpretation: {
			type: Schema.ObjectId,
			ref : "LogEntry"
		},
		member: {
			type: Schema.ObjectId,
			ref : "Interpretation"
		},
	}
 *
 */
@Injectable()
export class InterpretationBaseService {

    private interpretationCollection: AngularFirestoreCollection<Interpretation>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.interpretationCollection = afs.collection<Interpretation>('interpretation');
    }


    // CRUD METHODS

    /**
    * InterpretationService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Interpretation): Promise<DocumentReference> {
        return this.interpretationCollection.add(item);
    }

    /**
    * InterpretationService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.interpretationCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * InterpretationService.findByaction
    *   @description CRUD ACTION findByaction
    *   @param Objectid key Id della risorsa action da cercare
    *
    */
    findByAction(id: string): Observable<any[]> {
        return this.afs.collection('interpretation', ref => ref.where('action', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Interpretation;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * InterpretationService.findByentry
    *   @description CRUD ACTION findByentry
    *   @param Objectid key Id della risorsa entry da cercare
    *
    */
    findByEntry(id: string): Observable<any[]> {
        return this.afs.collection('interpretation', ref => ref.where('entry', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Interpretation;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * InterpretationService.findBymember
    *   @description CRUD ACTION findBymember
    *   @param Objectid key Id della risorsa member da cercare
    *
    */
    findByMember(id: string): Observable<any[]> {
        return this.afs.collection('interpretation', ref => ref.where('member', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Interpretation;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * InterpretationService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Interpretation> {
        return this.afs.doc<Interpretation>('interpretation/' + id);
    }

    /**
    * InterpretationService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Interpretation[]> {
        return this.afs.collection('interpretation').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Interpretation;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * InterpretationService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Interpretation>, item: Interpretation): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
