/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE journal-entryBaseService PLEASE EDIT ../journal-entry.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { JournalEntry } from '../../domain/habitopia_db/journal-entry';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../JournalEntry.service.ts
 */

/*
 * SCHEMA DB JournalEntry
 *
	{
		date: {
			type: 'Date',
			required : true
		},
		journalNotes: {
			type: 'String',
			required : true
		},
		latitude: {
			type: 'Decimal'
		},
		longitude: {
			type: 'Decimal'
		},
		share: {
			type: 'Boolean'
		},
		simpleReadableSummary: {
			type: 'String'
		},
		title: {
			type: 'String',
			required : true
		},
		votes: {
			type: 'Custom'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		action: {
			type: Schema.ObjectId,
			ref : "JournalEntry"
		},
		entry: {
			type: Schema.ObjectId,
			ref : "Interpretation"
		},
		journalEntry: {
			type: Schema.ObjectId,
			ref : "LogEntry"
		},
		member: {
			type: Schema.ObjectId,
			ref : "JournalEntry"
		},
		memberTarger: {
			type: Schema.ObjectId,
			ref : "JournalEntry"
		},
	}
 *
 */
@Injectable()
export class JournalEntryBaseService {

    private journalentryCollection: AngularFirestoreCollection<JournalEntry>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.journalentryCollection = afs.collection<JournalEntry>('journalentry');
    }


    // CRUD METHODS

    /**
    * JournalEntryService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: JournalEntry): Promise<DocumentReference> {
        return this.journalentryCollection.add(item);
    }

    /**
    * JournalEntryService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.journalentryCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * JournalEntryService.findByaction
    *   @description CRUD ACTION findByaction
    *   @param Objectid key Id della risorsa action da cercare
    *
    */
    findByAction(id: string): Observable<any[]> {
        return this.afs.collection('journalentry', ref => ref.where('action', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as JournalEntry;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * JournalEntryService.findBymember
    *   @description CRUD ACTION findBymember
    *   @param Objectid key Id della risorsa member da cercare
    *
    */
    findByMember(id: string): Observable<any[]> {
        return this.afs.collection('journalentry', ref => ref.where('member', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as JournalEntry;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * JournalEntryService.findBymemberTarger
    *   @description CRUD ACTION findBymemberTarger
    *   @param Objectid key Id della risorsa memberTarger da cercare
    *
    */
    findByMemberTarger(id: string): Observable<any[]> {
        return this.afs.collection('journalentry', ref => ref.where('memberTarger', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as JournalEntry;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * JournalEntryService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<JournalEntry> {
        return this.afs.doc<JournalEntry>('journalentry/' + id);
    }

    /**
    * JournalEntryService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<JournalEntry[]> {
        return this.afs.collection('journalentry').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as JournalEntry;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * JournalEntryService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<JournalEntry>, item: JournalEntry): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
