/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection } from '@angular/fire/firestore';
import { Observable } from 'rxjs';

// Import Services
import { InterpretationService } from '../../services/interpretation.service';
import { LogEntryService } from '../../services/log-entry.service';
import { JournalEntryService } from '../../services/journal-entry.service';
import { MemberService } from '../../services/member.service';
import { ActionService } from '../../services/action.service';

import { Interpretation } from '../../domain/habitopia_db/interpretation';
import { Action } from '../../domain/habitopia_db/action';
import { JournalEntry } from '../../domain/habitopia_db/journal-entry';
import { LogEntry } from '../../domain/habitopia_db/log-entry';
import { Member } from '../../domain/habitopia_db/member';

// START - USED SERVICES
/**
* InterpretationService.create
*	@description CRUD ACTION create
*
* LogEntryService.findByinterpretation
*	@description CRUD ACTION findByinterpretation
*	@param Objectid key Id della risorsa interpretation da cercare
*
* InterpretationService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* JournalEntryService.list
*	@description CRUD ACTION list
*
* MemberService.list
*	@description CRUD ACTION list
*
* ActionService.list
*	@description CRUD ACTION list
*
* InterpretationService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a  Interpretation
 */
@Component({
    selector: 'app-interpretation-edit',
    templateUrl: 'interpretation-edit.component.html',
    styleUrls: ['interpretation-edit.component.css']
})
export class InterpretationEditComponent implements OnInit {
    item: any = {};
    itemDoc: AngularFirestoreDocument<Interpretation>;
    isNew: Boolean = true;
    formValid: Boolean;

    listAction: Action[];
    listEntry: JournalEntry[];
    listInterpretation: Interpretation[];
    listMember: Member[];

    externalLogEntry: LogEntry[];

    constructor(
        private interpretationService: InterpretationService,
        private logentryService: LogEntryService,
        private journalentryService: JournalEntryService,
        private memberService: MemberService,
        private actionService: ActionService,
        private route: ActivatedRoute,
        private location: Location) {
        // Init list
        this.externalLogEntry = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.isNew = false;
                this.itemDoc = this.interpretationService.get(id);
                this.itemDoc.valueChanges().subscribe(item => this.item = item);

                this.logentryService.findByInterpretation(id).subscribe(list => this.externalLogEntry = list);
            }
            // Get relations
            this.actionService.list().subscribe(list => this.listAction = list);
            this.journalentryService.list().subscribe(list => this.listEntry = list);
            this.memberService.list().subscribe(list => this.listMember = list);
        });
    }



    /**
     * Save Interpretation
     *
     * @param {boolean} formValid Form validity check
     * @param Interpretation item Interpretation to save
     */
    save(formValid: boolean): void {
        this.formValid = formValid;
        if (formValid) {
            if (this.isNew) {
                // Create
                this.interpretationService.create(this.item);
                this.isNew = false;
            } else {
                // Update
                this.interpretationService.update(this.itemDoc, this.item);
            }
            this.goBack();
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }

}
