/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection } from '@angular/fire/firestore';
import { Observable } from 'rxjs';

// Import Services
import { RewardService } from '../../services/reward.service';
import { HabitService } from '../../services/habit.service';

import { Reward } from '../../domain/habitopia_db/reward';
import { Habit } from '../../domain/habitopia_db/habit';

// START - USED SERVICES
/**
* RewardService.create
*	@description CRUD ACTION create
*
* HabitService.findByrewards
*	@description CRUD ACTION findByrewards
*	@param Objectid key Id della risorsa rewards da cercare
*
* RewardService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* RewardService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a  Reward
 */
@Component({
    selector: 'app-reward-edit',
    templateUrl: 'reward-edit.component.html',
    styleUrls: ['reward-edit.component.css']
})
export class RewardEditComponent implements OnInit {
    item: any = {};
    itemDoc: AngularFirestoreDocument<Reward>;
    isNew: Boolean = true;
    formValid: Boolean;

    listRewards: Reward[];

    externalHabit: Habit[];

    constructor(
        private rewardService: RewardService,
        private habitService: HabitService,
        private route: ActivatedRoute,
        private location: Location) {
        // Init list
        this.externalHabit = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.isNew = false;
                this.itemDoc = this.rewardService.get(id);
                this.itemDoc.valueChanges().subscribe(item => this.item = item);

                this.habitService.findByRewards(id).subscribe(list => this.externalHabit = list);
            }
            // Get relations
        });
    }



    /**
     * Save Reward
     *
     * @param {boolean} formValid Form validity check
     * @param Reward item Reward to save
     */
    save(formValid: boolean): void {
        this.formValid = formValid;
        if (formValid) {
            if (this.isNew) {
                // Create
                this.rewardService.create(this.item);
                this.isNew = false;
            } else {
                // Update
                this.rewardService.update(this.itemDoc, this.item);
            }
            this.goBack();
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }

}
