/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection } from '@angular/fire/firestore';
import { Observable } from 'rxjs';

// Import Services
import { ActionService } from '../../services/action.service';
import { HabitService } from '../../services/habit.service';
import { JournalEntryService } from '../../services/journal-entry.service';
import { EvaluationService } from '../../services/evaluation.service';
import { InterpretationService } from '../../services/interpretation.service';

import { Action } from '../../domain/habitopia_db/action';
import { Interpretation } from '../../domain/habitopia_db/interpretation';
import { Evaluation } from '../../domain/habitopia_db/evaluation';
import { JournalEntry } from '../../domain/habitopia_db/journal-entry';
import { Habit } from '../../domain/habitopia_db/habit';

// START - USED SERVICES
/**
* ActionService.create
*	@description CRUD ACTION create
*
* HabitService.findByaction
*	@description CRUD ACTION findByaction
*	@param Objectid key Id della risorsa action da cercare
*
* JournalEntryService.findByaction
*	@description CRUD ACTION findByaction
*	@param Objectid key Id della risorsa action da cercare
*
* EvaluationService.findByaction
*	@description CRUD ACTION findByaction
*	@param Objectid key Id della risorsa action da cercare
*
* InterpretationService.findByaction
*	@description CRUD ACTION findByaction
*	@param Objectid key Id della risorsa action da cercare
*
* ActionService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* ActionService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a  Action
 */
@Component({
    selector: 'app-action-edit',
    templateUrl: 'action-edit.component.html',
    styleUrls: ['action-edit.component.css']
})
export class ActionEditComponent implements OnInit {
    item: any = {};
    itemDoc: AngularFirestoreDocument<Action>;
    isNew: Boolean = true;
    formValid: Boolean;

    listAction: Action[];

    externalInterpretation: Interpretation[];
    externalEvaluation: Evaluation[];
    externalJournalEntry: JournalEntry[];
    externalHabit: Habit[];

    constructor(
        private actionService: ActionService,
        private habitService: HabitService,
        private journalentryService: JournalEntryService,
        private evaluationService: EvaluationService,
        private interpretationService: InterpretationService,
        private route: ActivatedRoute,
        private location: Location) {
        // Init list
        this.externalInterpretation = [];
        this.externalEvaluation = [];
        this.externalJournalEntry = [];
        this.externalHabit = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.isNew = false;
                this.itemDoc = this.actionService.get(id);
                this.itemDoc.valueChanges().subscribe(item => this.item = item);

                this.interpretationService.findByAction(id).subscribe(list => this.externalInterpretation = list);
                this.evaluationService.findByAction(id).subscribe(list => this.externalEvaluation = list);
                this.journalentryService.findByAction(id).subscribe(list => this.externalJournalEntry = list);
                this.habitService.findByAction(id).subscribe(list => this.externalHabit = list);
            }
            // Get relations
        });
    }



    /**
     * Save Action
     *
     * @param {boolean} formValid Form validity check
     * @param Action item Action to save
     */
    save(formValid: boolean): void {
        this.formValid = formValid;
        if (formValid) {
            if (this.isNew) {
                // Create
                this.actionService.create(this.item);
                this.isNew = false;
            } else {
                // Update
                this.actionService.update(this.itemDoc, this.item);
            }
            this.goBack();
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }

}
