/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d41c8dfc0e2910e77977c56
*
* You will get 10% discount for each one of your friends
* 
*/
// BASE SERVICE
import { MemberBaseService } from './base/member.base.service';
import { User } from 'firebase';
import { Member } from '../domain/habitopia_db/member';




// start documentation
/**
 * Custom APIs
 *
 */
// end documentation

/**
 * YOU CAN OVERRIDE HERE MemberBaseService
 */
export class MemberService extends MemberBaseService {


    ensureMember(user: User) {
        this.get(user.uid).valueChanges().subscribe( member => {
            if (!member) {
                this.afs.collection<Member>('member').doc(user.uid).set({
                    id: user.uid,
                    displayName: user.displayName,
                    email: user.email,
                    trustSteps: 1
                });
            }
        });
    }
}
